services:
  backend:
    build:
      context: .
    environment:
      - "EMBEDDING_MODEL_PATH=ai-forever/sbert_large_nlu_ru"
      - "INIT_QA_DOCUMENTS=/code/resources/qa_final.csv"
      - "SEARCH_KEY=question_key"
      - "DEFAULT_TOP_K=10"
      - "ANSWER_THRESHOLD=0.53"
    ports:
      - "8000:8000"
    volumes:
      - "./resources:/code/resources"
    tty: true
    stdin_open: true
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              count: 1
              capabilities: [ gpu ]
        limits:
          memory: 15000M